CREATE TABLE EMP1 (ID NUMBER,NAME VARCHAR2(50),DEPT VARCHAR2(50),CONSTRAINT my_emp_id_pk PRIMARY KEY (ID));
CREATE TABLE DEPT1 (ID NUMBER,NAME VARCHAR2(50), LOCATION VARCHAR2(50),CONSTRAINT my_dept_id_pk PRIMARY KEY (ID));
ALTER TABLE EMP1 ADD DEPT_ID NUMBER;
ALTER TABLE EMP1 ADD CONSTRAINT my_emp_dept_id_fk FOREIGN KEY (DEPT_ID) REFERENCES DEPT1(ID);
ALTER TABLE EMP1 ADD COMMISSION NUMBER(5,2);
ALTER TABLE EMP1 ADD CONSTRAINT emp_commission_ck CHECK (COMMISSION > 0);
